// Seeds products + lanes into the SQLite db.
// Layout: 6 rows total = 3 double-row blocks, 2 aisles (the corrected, honest
// layout — NOT the flawed 8-row version). Bakery & Snacks = K1-K3, Meals = M1-M3.
// 27 positions/row -> 162 total floor positions.
//
// Lane assignment order comes from lane_plan.json, generated by
// build_slotting.py from real order-fulfillment data (a parsed 180-order
// Monday shipout batch) instead of blended cross-channel Shopify sales:
//   1. Golden zone — within each section, fastest-moving product first
//      (Row 1 nearest the aisle entrance, working back through Row 2/3).
//   2. Order-affinity clustering — within a row, products frequently
//      ordered together are placed in adjacent lanes.
// See Hummus_Fit_Crate_Build_Sheet.xlsx for the full methodology and the
// per-lane crate counts this same file drives.
const fs = require('fs');
const path = require('path');

function capFor(p) {
  if (p.cat === 'meal') return 24;
  if (p.cat === 'muffin') return 24;
  if (p.cat === 'oats') return 28;
  if (p.cat === 'snack') {
    if (/gree-yo|pudding/i.test(p.name)) return 28;
    if (/buff crisp bar/i.test(p.name)) return 48;
    return 24; // poppers, energy bites, etc.
  }
  return 24;
}

function runSeed(db) {
  const products = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'products.json'), 'utf8')
  );
  const lanePlan = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'lane_plan.json'), 'utf8')
  );

  const insertProduct = db.prepare(`
    INSERT INTO products (name, category, u30, cap, crate_w, crate_d, crate_h)
    VALUES (@name, @category, @u30, @cap, 21.65, 15.70, 10.70)
    ON CONFLICT(name) DO UPDATE SET
      category=excluded.category, u30=excluded.u30, cap=excluded.cap
  `);

  const insertLane = db.prepare(`
    INSERT OR IGNORE INTO lanes (code, section, row_num, position_num)
    VALUES (?, ?, ?, ?)
  `);

  // Upsert (not OR IGNORE) so that re-running this on a re-slotted room
  // actually moves products to their new lanes instead of leaving the old
  // assignment in place. crates_current resets to 0 on a real placement
  // change — that's correct: a physical re-slot means staff are recounting
  // and restocking into the new spot, not carrying over an old count.
  const insertAssignment = db.prepare(`
    INSERT INTO lane_assignments (lane_id, product_id, crates_current, max_stack)
    VALUES (?, ?, 0, 5)
    ON CONFLICT(lane_id) DO UPDATE SET
      product_id = excluded.product_id,
      crates_current = 0,
      max_stack = excluded.max_stack,
      updated_at = CURRENT_TIMESTAMP
    WHERE lane_assignments.product_id IS NOT excluded.product_id
  `);

  const seed = db.transaction(() => {
    for (const p of products) {
      insertProduct.run({
        name: p.name,
        category: p.cat,
        u30: p.u30,
        cap: capFor(p),
      });
    }

    const POSITIONS_PER_ROW = 27;
    const sections = [
      { key: 'bakery', rows: ['K1', 'K2', 'K3'] },
      { key: 'meals', rows: ['M1', 'M2', 'M3'] },
    ];
    for (const s of sections) {
      s.rows.forEach((rowLabel, rowIdx) => {
        for (let pos = 1; pos <= POSITIONS_PER_ROW; pos++) {
          const code = `${rowLabel}-${String(pos).padStart(2, '0')}`;
          insertLane.run(code, s.key, rowIdx + 1, pos);
        }
      });
    }

    const nameToProductId = {};
    for (const row of db.prepare('SELECT id, name FROM products').all()) {
      nameToProductId[row.name] = row.id;
    }
    const codeToLaneId = {};
    for (const row of db.prepare('SELECT id, code FROM lanes').all()) {
      codeToLaneId[row.code] = row.id;
    }

    let assigned = 0, skippedNoProduct = 0, skippedNoLane = 0;
    for (const sectionKey of Object.keys(lanePlan)) {
      for (const lane of lanePlan[sectionKey].lanes) {
        const laneId = codeToLaneId[lane.code];
        const productId = nameToProductId[lane.product];
        if (!laneId) { skippedNoLane++; continue; }
        if (!productId) { skippedNoProduct++; continue; }
        insertAssignment.run(laneId, productId);
        assigned++;
      }
    }

    const totalLanes = Object.values(lanePlan).reduce((n, s) => n + s.total_positions, 0);
    return {
      products: products.length,
      lanes: totalLanes,
      assigned,
      skippedNoProduct,
      skippedNoLane,
    };
  });

  return seed();
}

module.exports = { runSeed };

// Allow running directly: `node seed.js`
if (require.main === module) {
  const db = require('./db');
  const result = runSeed(db);
  console.log('Seed complete:', result);
}
